language: node_js
node_js:
  - "4.4"
before_script:
  - npm install -g gulp
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: 
  - gulp
  - npm test
after_success:
  - rm src -rf
  - rm node_modules -rf
  - npm install --production
  - ls
  - bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "e4c5ebf2a3cf"
  - COMMIT_AUTHOR_EMAIL: "ryan.nhg@gmail.com"