version: '3'
services:

  mongo:
    image: mongo

  web:
    image: ryannhg/jangle
    build: 
      context: ./
      dockerfile: Dockerfile
    links:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - ./elm-package.json:/usr/src/app/elm-package.json
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./nodemon.json:/usr/src/app/nodemon.json
      - ./gulpfile.js:/usr/src/app/gulpfile.js
      - ./web:/usr/src/app/web
      - ./server:/usr/src/app/server
